"""Init

Revision ID: bf1e56601dbf
Revises: 
Create Date: 2025-03-22 00:34:38.592860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf1e56601dbf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_index(op.f('ix_activities_name'), 'activities', ['name'], unique=False)
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildings_address'), 'buildings', ['address'], unique=True)
    op.create_index(op.f('ix_buildings_id'), 'buildings', ['id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_numbers', sa.String(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_table('organization_activity',
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], )
    )

    # ### end Alembic commands ###
    activities_table = sa.table(
        "activities",
        sa.Column("id", sa.Integer),
        sa.Column("name", sa.String),
        sa.Column("parent_id", sa.Integer),
    )

    buildings_table = sa.table(
        "buildings",
        sa.Column("id", sa.Integer),
        sa.Column("address", sa.String),
        sa.Column("latitude", sa.Float),
        sa.Column("longitude", sa.Float),
    )

    organizations_table = sa.table(
        "organizations",
        sa.Column("id", sa.Integer),
        sa.Column("name", sa.String),
        sa.Column("phone_numbers", sa.String),
        sa.Column("building_id", sa.Integer),
    )

    organization_activity_table = sa.table(
        "organization_activity",
        sa.Column("organization_id", sa.Integer),
        sa.Column("activity_id", sa.Integer),
    )

    # Вставляем данные в таблицу activities
    op.bulk_insert(
        activities_table,
        [
            {"name": "Еда", "parent_id": None},
            {"name": "Мясная продукция", "parent_id": 1},
            {"name": "Молочная продукция", "parent_id": 1},
            {"name": "Автомобили", "parent_id": None},
            {"name": "Грузовые", "parent_id": 4},
            {"name": "Легковые", "parent_id": 4},
            {"name": "Запчасти", "parent_id": 4},
            {"name": "Аксессуары", "parent_id": 4},
        ],
    )

    # Вставляем данные в таблицу buildings
    op.bulk_insert(
        buildings_table,
        [
            {"address": "ул. Ленина, 10", "latitude": 55.7558, "longitude": 37.6176},
            {"address": "ул. Пушкина, 5", "latitude": 55.7560, "longitude": 37.6178},
            {"address": "ул. Гагарина, 15", "latitude": 55.7500, "longitude": 37.6200},
        ],
    )

    # Вставляем данные в таблицу organizations
    op.bulk_insert(
        organizations_table,
        [
            {"name": "Организация 1", "phone_numbers": "+7 999 111 11 11", "building_id": 1},
            {"name": "Организация 2", "phone_numbers": "+7 999 222 22 22", "building_id": 1},
            {"name": "Организация 3", "phone_numbers": "+7 999 333 33 33", "building_id": 2},
            {"name": "Организация 4", "phone_numbers": "+7 999 444 44 44", "building_id": 3},
        ],
    )

    # Вставляем данные в таблицу organization_activity (связи организаций и деятельностей)
    op.bulk_insert(
        organization_activity_table,
        [
            {"organization_id": 1, "activity_id": 1},  # Организация 1 -> Еда
            {"organization_id": 2, "activity_id": 3},  # Организация 2 -> Молочная продукция
            {"organization_id": 3, "activity_id": 5},  # Организация 3 -> Грузовые
            {"organization_id": 4, "activity_id": 7},  # Организация 4 -> Запчасти
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_activity')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_buildings_id'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_address'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_activities_name'), table_name='activities')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
